### ISSUE TITLE
 Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by itsmesinghavneet** [skaterdav85/ember-testing#1]
Hi, I am new to ember and find this error while serving I have followed the steps ...
npm install 
bower install 
the error is:
  throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/home/cb/Desktop/unit_test/ember-testing/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by iamdtang** [comment]
This repo is pretty old and uses Ember CLI 1.13. I'm guessing you have Ember CLI version 2.x installed hence why it isn't working. If you really want to run this project, I'd suggest installing Ember CLI 1.13. Hope that helps.
